<a href="https://colab.research.google.com/github/ncphung1405/bai1/blob/main/bai_tap_sinh_mau_ngau_nhien.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sử dụng thư viện Numpy

1. Sinh mẫu ngẫu nhiên bằng hàm arange trong khoảng [-15, 27] với khoảng cách là 0.7 và in kết quả ra màn hình

In [1]:
import numpy as np
np.arange(-15,27,0.7)


array([-15. , -14.3, -13.6, -12.9, -12.2, -11.5, -10.8, -10.1,  -9.4,
        -8.7,  -8. ,  -7.3,  -6.6,  -5.9,  -5.2,  -4.5,  -3.8,  -3.1,
        -2.4,  -1.7,  -1. ,  -0.3,   0.4,   1.1,   1.8,   2.5,   3.2,
         3.9,   4.6,   5.3,   6. ,   6.7,   7.4,   8.1,   8.8,   9.5,
        10.2,  10.9,  11.6,  12.3,  13. ,  13.7,  14.4,  15.1,  15.8,
        16.5,  17.2,  17.9,  18.6,  19.3,  20. ,  20.7,  21.4,  22.1,
        22.8,  23.5,  24.2,  24.9,  25.6,  26.3,  27. ])

2. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 2.7 std = 1.2 và size = 40
In kết quả ra màn hình

In [2]:
 np.random.normal(loc = 2.7, scale = 1.2, size = 40)

array([ 2.64037927,  2.19886958,  1.70385607,  2.91400149,  1.72858906,
        1.93434512,  0.97254605,  1.89019953,  3.4621967 ,  3.14704957,
        1.79792346,  2.1775701 ,  3.89749553,  2.80199108,  3.40136661,
        3.03516386, -0.57510033,  1.7997329 ,  1.83790418,  4.1108094 ,
        1.38926524,  2.85865078,  1.29663534,  2.76869723,  5.79494733,
        1.80810384,  5.76035935,  3.26673288,  1.25811095,  2.04032819,
        1.70664882,  3.58022982,  2.93487687,  2.43798796,  4.26876431,
        0.64813412,  2.53695285,  1.37072114,  1.62649744,  4.00460177])

3. Sinh mẫu ngẫu nhiên từ vector ['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'] 

với kích thước là 17 theo phân phối chuẩn

In [6]:
np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'], 17)

array(['Britain', 'Viet Nam', 'Viet Nam', 'Viet Nam', 'Singapore',
       'Viet Nam', 'Singapore', 'Russia', 'Singapore', 'Britain',
       'Britain', 'Singapore', 'Britain', 'Britain', 'France', 'Britain',
       'Viet Nam'], dtype='<U9')

4. Sinh mẫu ngẫu nhiên ở câu 3 nhưng không theo phân phối chuẩn mà theo 1 vector đặc tả giá trị xác suất do bạn chọn

In [22]:
sample_8 = np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'], 9, p = [0.4, 0.2, 0.1, 0.1, 0.2])
print(sample_8)

['Viet Nam' 'Viet Nam' 'Singapore' 'Viet Nam' 'Britain' 'Britain'
 'Britain' 'Russia' 'Viet Nam']


Sử dụng thư việc scipy.stats để sinh mẫu ngẫu nhiên

1. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 12.7, std = 2.6 và size = 30. In kết quả ra màn hình

In [23]:
#Code
from scipy import stats
stats.norm.rvs(loc = 12.7, scale = 2.6, size = 30)

array([10.09126685, 13.42117596, 11.31318916, 13.61274283,  7.91374034,
       13.76559921,  9.09173452, 13.39215062, 12.84106529, 12.18501815,
       10.0203266 , 10.43125315, 11.05384495, 14.05482399, 13.45081107,
       11.63344235, 12.51982958, 11.91426138, 12.5782205 , 15.75600812,
       11.04542162, 15.20234502, 10.832442  , 13.35592301,  7.25696335,
       16.39187417, 10.70463444, 11.82113372, 10.60101592, 12.38820168])

2. Hãy sinh một mẫu ngẫu nhiên theo phân phối Poisson

In [24]:
stats.poisson.rvs(loc=100,
                   mu=20,
                   size=50)


array([120, 127, 117, 122, 119, 116, 122, 118, 117, 118, 118, 122, 117,
       119, 120, 119, 114, 119, 126, 116, 117, 123, 119, 121, 113, 120,
       121, 106, 120, 118, 122, 116, 127, 113, 115, 122, 117, 121, 114,
       110, 114, 129, 115, 114, 129, 120, 111, 121, 120, 125])