<a href="https://colab.research.google.com/github/ncphung1405/bai1/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Đây là chương trình đầu tiên**

In [ ]:
#1.Numpy:
  #- Tạo ma trận:
import numpy as np 
a = np.array(([(2,3,4,5), (4,6,4,8)],
              [(2,4,6,2), (3,6,7,2)],
              [(4,6,3,2), (4,7,9,0)]),dtype=int)
print("Ma trận A= ",a)

  #- Tính tổng 2 ma trận:
import numpy as np
a = np.array(([(2,3,5,6), (2,7,8,4)]),dtype = int)
b = np.array(([(2,9,0,1), (7,4,7,8)]),dtype = int) 
print("ma trận A= ",a)
print("ma trận B= ",b)
print("ma trận A+B= ", a+b)

  #- Tính tích hai ma trận:
import numpy as np 
a = np.array(([((6,8),(3,9)), ((6,3),(8,3))]),dtype = int)
b = np.array(([(5,7,3,7), (6,2,7,2)]),dtype = int)
print("ma trận C= ",a)
print("ma trận D= ",b)
print("ma trận C*D ", a @ b)
 

Ma trận A=  [[[2 3 4 5]
  [4 6 4 8]]

 [[2 4 6 2]
  [3 6 7 2]]

 [[4 6 3 2]
  [4 7 9 0]]]
ma trận A=  [[2 3 5 6]
 [2 7 8 4]]
ma trận B=  [[2 9 0 1]
 [7 4 7 8]]
ma trận A+B=  [[ 4 12  5  7]
 [ 9 11 15 12]]
ma trận C=  [[[6 8]
  [3 9]]

 [[6 3]
  [8 3]]]
ma trận D=  [[5 7 3 7]
 [6 2 7 2]]
ma trận C*D  [[[78 58 74 58]
  [69 39 72 39]]

 [[48 48 39 48]
  [58 62 45 62]]]
